export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_STARTED = "FETCH_EMPLOYEES_STARTED"
export const FETCH_EMPLOYEES_FINISHED = "FETCH_EMPLOYEES_FINISHED"
export const SET_EMPLOYEES = "SET_EMPLOYEES"

export const SET_ROLE_FILTER = 'SET_ROLE_FILTER';
export const SET_ARCHIVED_FILTER = 'SET_ARCHIVED_FILTER';

export const SET_BIRTHDAY_SORT_ORDER = 'SET_BIRTHDAY_SORT_ORDER';
export const SET_NAME_SORT_ORDER = 'SET_NAME_SORT_ORDER';