export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_STARTED = "FETCH_EMPLOYEES_STARTED"
export const FETCH_EMPLOYEES_FINISHED = "FETCH_EMPLOYEES_FINISHED"
export const SET_EMPLOYEES = "SET_EMPLOYEES"